# Generated by Django 4.0.6 on 2022-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_empresa',
            name='tipo_empresa_id',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='margen_contribucion_Total',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tipo_empresa',
            name='tipo_empresa',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
