# Generated by Django 4.0.6 on 2022-09-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0003_producto_p_v_u_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costo_variable',
            name='cantidad_compra',
        ),
    ]
