# Generated by Django 4.0.6 on 2022-09-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinerApp', '0005_remove_empresa_cantidad_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tipo_empresa_id',
        ),
        migrations.DeleteModel(
            name='TIPO_EMPRESA',
        ),
    ]
